DROP TABLE IF EXISTS room;
DROP TABLE IF EXISTS student;
DROP TABLE IF EXISTS faculty;
DROP TABLE IF EXISTS university;
DROP TABLE IF EXISTS block;
DROP TABLE IF EXISTS dormitory;

CREATE TABLE dormitory (
                           id INT GENERATED by DEFAULT AS IDENTITY PRIMARY KEY,
                           name VARCHAR(50) NOT NULL,
                           address VARCHAR(300) NOT NULL,
                           block_number INT NOT NULL
);

CREATE TABLE block(
                      id INT GENERATED by DEFAULT AS IDENTITY PRIMARY KEY,
                      dormitory_id INT NOT NULL,
                      FOREIGN KEY(dormitory_id) REFERENCES dormitory(id),
                      name VARCHAR(1) NOT NULL
);

CREATE TABLE university(
                           id INT GENERATED by DEFAULT AS IDENTITY PRIMARY KEY,
                           name VARCHAR(50) NOT NULL
);

CREATE TABLE faculty(
                        id INT GENERATED by DEFAULT AS IDENTITY PRIMARY KEY,
                        name VARCHAR(50) NOT NULL,
                        university_id INT,
                        FOREIGN KEY (university_id) REFERENCES university(id)
);

CREATE TABLE student(
                        id INT GENERATED by DEFAULT AS IDENTITY PRIMARY KEY,
                        identity_number VARCHAR(11) UNIQUE NOT NULL,
                        name VARCHAR(40) NOT NULL,
                        surname VARCHAR(20) NOT NULL,
                        age INT,
                        profession VARCHAR(80) NOT NULL,
                        schoolStatus INT NOT NULL,
                        faculty_id INT NOT NULL,
                        FOREIGN KEY(faculty_id) REFERENCES faculty(id),
                        phone VARCHAR(14) NOT NULL,
                        email VARCHAR(50) UNIQUE NOT NULL,
                        dormitory_starts DATE NOT NULL,
                        dormitory_finishes DATE NOT NULL
);

CREATE TABLE room(
                     id INT GENERATED by DEFAULT AS IDENTITY PRIMARY KEY,
                     room_number VARCHAR(3) NOT NULL,
                     number_of_students INT,
                     block_id INT,
                     FOREIGN KEY(block_id) REFERENCES block(id),
                     dormitory_id INT,
                     FOREIGN KEY(dormitory_id) REFERENCES dormitory(id)
);

INSERT INTO dormitory(name, address, block_number) VALUES ('Alaaddin Yurdu', 'Konya/Selçuk Üniversitesi Kampüsü', 3),
                                                          ('Ali Ulvi Yurdu', 'Bosna Hersek Mahallesi', 2),
                                                          ('Mevlana Yurdu', 'Yazır Mahallesi', 2);

INSERT INTO block(dormitory_id, name) VALUES (1,'A'),
                                             (1,'B'),
                                             (1,'C'),
                                             (2,'A'),
                                             (2,'B'),
                                             (3,'A'),
                                             (3,'B');
INSERT INTO university(name) VALUES ('Selcuk University');

INSERT INTO faculty(name,university_id) VALUES ('Engineering',1),
                                               ('Medical',1),
                                               ('Social Sceince',1),
                                               ('Foreign Languages',1),
                                               ('Sceince',1),
                                               ('Literatur',1);

INSERT INTO student(identity_number, name, surname, age, profession, schoolStatus, phone, email, dormitory_starts, dormitory_finishes, faculty_id) VALUES ('56985679156','Mahmut', 'Yirmi',20 ,'Engineering',2, '+905869563578','mahmutyrm@gmail.com','2021-09-25','2025-06-15',1);



INSERT INTO room(room_number,block_id,dormitory_id,number_of_students) VALUES ('100',1,1,4);